services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo_catalog
    environment:
      - 'MONGO_INITDB_DATABASE=catalog'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
