server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,liveness,readiness,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

logging:
  config: classpath:logback.xml

cloud:
  aws:
    region:
      static: us-east-2
  config:
    server:
      aws:
        paramstore:
          enabled: true

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  data:
    mongodb:
      uri: ${/catalog-api/DATABASE_URI:mongodb://root:secret@localhost:27017/catalog}
      uuid-representation: standard

system:
  id-service: catalog-api
  collection:
    product: product