server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,liveness,readiness,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

logging:
  config: classpath:logback.xml

spring:
  profiles:
    active: prod
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  data:
    mongodb:
      uri: ${/config/catalog-api_prod/mongoUri}
      uuid-representation: standard

system:
  id-service: catalog-api
  collection:
    product: product
  sns:
    product: product.fifo

aws:
  paramstore:
    enabled: true
    name: catalog-api
    prefix: /config
    profileSeparator: _
    failFast: false